"""Shared constants for the pipeline.

Centralizes magic numbers and configuration values.
"""

_DEFAULT_BATCH_SIZE = 100
_LARGE_BATCH_SIZE = 1000
_VIDEO_BATCH_SIZE = 10
_TEXT_BATCH_SIZE = 100
_GPU_BATCH_SIZE = 10000
_CORRUPTION_BATCH_SIZE = 100
_TRAINING_BATCH_SIZE = 1024
_EVAL_BATCH_SIZE = 100
_SYNTHETIC_BATCH_SIZE = 64

_DEFAULT_CPUS = 4
_DEFAULT_CPUS_PER_GPU = 8
_DEFAULT_GPUS = 1
_DEFAULT_NUM_CPUS = 1

_DEFAULT_OBJECT_STORE_GB = 20_000_000_000  # 20 GB in bytes

# Configuration defaults
_DEFAULT_CHECKPOINT_INTERVAL = 1000
_DEFAULT_PREFETCH_BUFFER_SIZE = 4
_DEFAULT_DEDUP_METHOD = "both"
_DEFAULT_COMPUTE_MODE = "auto"
_DEFAULT_COMPRESSION = "snappy"
_DEFAULT_NUM_ROWS_PER_FILE = 1_000_000

_MAX_CHUNK_SIZE_BYTES = 100 * 1024 * 1024
_MAX_DATASET_SIZE_BYTES = 100 * 1024 * 1024

_DEFAULT_EMBEDDING_DIM = 768
_DEFAULT_SIMILARITY_THRESHOLD = 0.95
_DEFAULT_QUALITY_THRESHOLD = 0.5

_DEFAULT_FRAME_RATE = 30
_DEFAULT_RESOLUTION = (224, 224)
_DEFAULT_VIDEO_RESOLUTION = (1280, 720)
_NORMALIZATION_DIVISOR = 255.0

_DEFAULT_MAX_LENGTH = 4096
_DEFAULT_MIN_LENGTH = 10

_DEFAULT_SAMPLE_RATE = 100

_VISUALIZATION_SAMPLE_SIZE = 10
_MAX_VIDEOS = 5

_DEFAULT_LIMIT = 10
_DEFAULT_MAX_DISTANCE = 0.3

_DEFAULT_TABLE_NAME = "embeddings"

_DEFAULT_SAFETY_MARGIN = 0.1
_DEFAULT_DEVICE_ID = 0

_DEFAULT_MAX_DURATION = 60.0
_DEFAULT_LANGUAGE = "en"

_DEFAULT_ESTIMATED_OUTPUT_SIZE_BYTES = 10 * 1024 * 1024 * 1024

# Ray infrastructure constants
_DEFAULT_RAY_NAMESPACE = "multimodal-pipeline"
_DEFAULT_RAY_DASHBOARD_PORT = 8265
_DEFAULT_RAY_DASHBOARD_HOST = "0.0.0.0"
_DEFAULT_RAY_TASK_TIMEOUT = 300.0  # 5 minutes
_DEFAULT_RAY_ACTOR_TIMEOUT = 600.0  # 10 minutes
_DEFAULT_RAY_SHUTDOWN_TIMEOUT = 30.0  # 30 seconds
_MAX_RAY_RETRIES = 2  # Maximum retries for Ray tasks

