# AWS Secrets Manager Integration
# Uses External Secrets Operator to sync secrets from AWS Secrets Manager
# Note: Requires External Secrets Operator to be installed first

apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets-system
  labels:
    name: external-secrets-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: pipeline-production
  labels:
    name: pipeline-production
    environment: production
    cloud-provider: aws
---
# Service Account for External Secrets Operator with IRSA
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: external-secrets-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/external-secrets-operator-role
  labels:
    app: external-secrets
---
# SecretStore for AWS Secrets Manager
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: pipeline-production
  labels:
    app: external-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets-system
---
# ClusterSecretStore for cluster-wide access (alternative to namespace-scoped SecretStore)
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager-cluster
  labels:
    app: external-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets-system
---
# ExternalSecret for pipeline AWS credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pipeline-aws-secrets
  namespace: pipeline-production
  labels:
    app: multimodal-pipeline
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: pipeline-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app: multimodal-pipeline
        annotations:
          managed-by: external-secrets
      data:
        # Template allows for transformation if needed
        aws-access-key-id: "{{ .aws_access_key_id }}"
        aws-secret-access-key: "{{ .aws_secret_access_key }}"
  data:
  - secretKey: aws-access-key-id
    remoteRef:
      key: pipeline/aws-credentials
      property: access-key-id
  - secretKey: aws-secret-access-key
    remoteRef:
      key: pipeline/aws-credentials
      property: secret-access-key
  - secretKey: database-password
    remoteRef:
      key: pipeline/database
      property: password
---
# ExternalSecret for database credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pipeline-database-secrets
  namespace: pipeline-production
  labels:
    app: multimodal-pipeline
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: pipeline-database-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app: multimodal-pipeline
        annotations:
          managed-by: external-secrets
  data:
  - secretKey: database-password
    remoteRef:
      key: pipeline/database
      property: password
  - secretKey: database-host
    remoteRef:
      key: pipeline/database
      property: host
  - secretKey: database-port
    remoteRef:
      key: pipeline/database
      property: port
  - secretKey: database-username
    remoteRef:
      key: pipeline/database
      property: username

