# External Secrets Operator Configuration
# Replaces custom secret manager with External Secrets Operator

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: pipeline-production
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
---
# External Secret - Replaces custom secret management
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pipeline-secrets
  namespace: pipeline-production
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: pipeline-secrets
    creationPolicy: Owner
  data:
  - secretKey: aws-access-key-id
    remoteRef:
      key: pipeline/aws-credentials
      property: access-key-id
  - secretKey: aws-secret-access-key
    remoteRef:
      key: pipeline/aws-credentials
      property: secret-access-key
---
# Sealed Secret (alternative for GitOps)
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pipeline-sealed-secret
  namespace: pipeline-production
spec:
  encryptedData:
    aws-access-key-id: <encrypted-value>
    aws-secret-access-key: <encrypted-value>
  template:
    metadata:
      name: pipeline-secrets
      namespace: pipeline-production
    type: Opaque

