# Production-ready Kubernetes deployment configuration
# Includes: HPA, PDB, health checks, security contexts, resource quotas

apiVersion: v1
kind: Namespace
metadata:
  name: pipeline-production
  labels:
    name: pipeline-production
    environment: production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: multimodal-pipeline-config
  namespace: pipeline-production
data:
  config.yaml: |
    input_paths:
      - "s3://bucket/videos/"
      - "s3://bucket/text/"
    output_path: "s3://bucket/curated/"
    enable_gpu_dedup: true
    num_gpus: 8
    streaming: true
    checkpoint_interval: 1000
    enable_profiling: true
    enable_incremental_processing: true
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: pipeline-production
type: Opaque
stringData:
  access-key-id: ""  # Set via kubectl or CI/CD
  secret-access-key: ""  # Set via kubectl or CI/CD
---
apiVersion: v1
kind: Service
metadata:
  name: multimodal-pipeline-service
  namespace: pipeline-production
  labels:
    app: multimodal-pipeline
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: prometheus-metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: multimodal-pipeline
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multimodal-pipeline
  namespace: pipeline-production
  labels:
    app: multimodal-pipeline
    version: v1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: multimodal-pipeline
  template:
    metadata:
      labels:
        app: multimodal-pipeline
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      # Security context
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      
      # Service account for RBAC
      serviceAccountName: pipeline-service-account
      
      # Init container for setup
      initContainers:
      - name: init-config
        image: busybox:1.36
        command: ['sh', '-c', 'echo "Initializing pipeline configuration"']
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      
      containers:
      - name: pipeline
        image: multimodal-pipeline:latest  # Use specific tag in production
        imagePullPolicy: Always
        
        # Security context
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false  # Set to true if possible
        
        # Resource requests and limits
        resources:
          requests:
            memory: "32Gi"
            cpu: "16"
            nvidia.com/gpu: "8"
          limits:
            memory: "64Gi"
            cpu: "32"
            nvidia.com/gpu: "8"
        
        # Environment variables
        env:
        - name: RAY_ADDRESS
          value: "ray://ray-head-service.pipeline-production.svc.cluster.local:10001"
        - name: OUTPUT_PATH
          value: "s3://bucket/curated/"
        - name: HEALTH_CHECK_PORT
          value: "8080"
        - name: LOG_LEVEL
          value: "INFO"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: secret-access-key
        
        # Volume mounts
        volumeMounts:
        - name: config
          mountPath: /app/config
          readOnly: true
        - name: tmp
          mountPath: /tmp
        
        # Health checks
        livenessProbe:
          httpGet:
            path: /live
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        
        # Startup probe for slow-starting containers
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 30
      
      volumes:
      - name: config
        configMap:
          name: multimodal-pipeline-config
      - name: tmp
        emptyDir: {}
      
      # Node selector for GPU nodes
      nodeSelector:
        accelerator: nvidia-gpu
      
      # Tolerations for GPU nodes
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      
      # Affinity for pod distribution
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - multimodal-pipeline
              topologyKey: kubernetes.io/hostname
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: multimodal-pipeline-hpa
  namespace: pipeline-production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: multimodal-pipeline
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: multimodal-pipeline-pdb
  namespace: pipeline-production
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: multimodal-pipeline
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-service-account
  namespace: pipeline-production
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipeline-role
  namespace: pipeline-production
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-role-binding
  namespace: pipeline-production
subjects:
- kind: ServiceAccount
  name: pipeline-service-account
  namespace: pipeline-production
roleRef:
  kind: Role
  name: pipeline-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: multimodal-pipeline-cluster
  namespace: pipeline-production
spec:
  rayVersion: '2.10.0'
  enableInTreeAutoscaling: true
  autoscalerOptions:
    upscalingMode: "Default"
    idleTimeoutSeconds: 60
  headGroupSpec:
    serviceType: ClusterIP
    rayStartParams:
      dashboard-host: '0.0.0.0'
      num-cpus: '4'
    template:
      spec:
        serviceAccountName: pipeline-service-account
        containers:
        - name: ray-head
          image: rayproject/ray:2.10.0-gpu
          resources:
            requests:
              cpu: "4"
              memory: "8Gi"
            limits:
              cpu: "4"
              memory: "8Gi"
          ports:
          - containerPort: 8265
            name: dashboard
          - containerPort: 10001
            name: client
        nodeSelector:
          accelerator: nvidia-gpu
  workerGroupSpecs:
  - replicas: 4
    minReplicas: 2
    maxReplicas: 10
    groupName: gpu-workers
    rayStartParams:
      num-cpus: '8'
      num-gpus: '2'
    template:
      spec:
        serviceAccountName: pipeline-service-account
        containers:
        - name: ray-worker
          image: rayproject/ray:2.10.0-gpu
          resources:
            requests:
              nvidia.com/gpu: "2"
              cpu: "8"
              memory: "32Gi"
            limits:
              nvidia.com/gpu: "2"
              cpu: "8"
              memory: "32Gi"
          ports:
          - containerPort: 8265
            name: dashboard
        nodeSelector:
          accelerator: nvidia-gpu
        tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule

