# cert-manager Configuration for On-Premises
# Automatic TLS certificate management using Let's Encrypt or internal CA

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@example.com
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
    - http01:
        ingress:
          class: nginx
---
# Internal CA Issuer (for internal-only services)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: internal-ca-issuer
spec:
  ca:
    secretName: internal-ca-key-pair
---
# Certificate for pipeline service
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pipeline-tls-cert
  namespace: pipeline-production
spec:
  secretName: pipeline-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - pipeline.example.com
  - pipeline-api.example.com

